server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.115.76.10:3306/ooad_project?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
    username: ooad
    password: ooadpassword

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  # Hot reload in dev
  devtools:
    add-properties: true

  servlet:
    multipart:
      enabled: true
      location: /data/
      max-file-size: 1MB
      max-request-size: 5MB
      resolve-lazily: false
      file-size-threshold: 0

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml