server:
  port: 80

spring:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 3000
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0

  profiles:
    active: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.115.76.10:3306/ooad_project?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
    username: ooad
    password: ooadpassword

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  jackson:
    default-property-inclusion: non_null
    serialization:
      fail-on-empty-beans: false

  # Hot reload in dev
  devtools:
    add-properties: true

  servlet:
    multipart:
      enabled: true
      location: /data/
      max-file-size: 5000MB
      max-request-size: 5000MB
      resolve-lazily: false
      file-size-threshold: 0

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml
