server:
  port: 80
  servlet:
    encoding:
      force: true
      charset: utf-8
      enabled: true
  tomcat:
    uri-encoding: UTF-8

spring:
  profiles:
    active: prod

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  redis:
    timeout: 3000
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0

  data:
    redis:
      repositories:
        enabled: false

  jackson:
    default-property-inclusion: non_null
    serialization:
      fail-on-empty-beans: false
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  servlet:
    multipart:
      enabled: true
      location: /data/
      max-file-size: 5000MB
      max-request-size: 5000MB
      resolve-lazily: false
      file-size-threshold: 0

  mail:
    default-encoding: utf-8
    port: 465
    protocol: smtps
    properties:
      mail:
        smtp:
          ssl:
            enabled: true
          auth: true
          starttls:
            enable: true
            required: true