-- MySQL Script generated by MySQL Workbench
-- Fri Nov  6 20:48:38 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema gamercenter
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gamercenter
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gamercenter` DEFAULT CHARACTER SET utf8 ;
USE `gamercenter` ;

-- -----------------------------------------------------
-- Table `gamercenter`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gamercenter`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `balance` DECIMAL(9,2) NOT NULL DEFAULT 0,
  `role` VARCHAR(10) NULL COMMENT 'a/p/d\nadmin/player/develop',
  `avatar` VARCHAR(255) NULL,
  `bio` VARCHAR(2048) NULL,
  `is_online` TINYINT NULL DEFAULT 0,
  `is_locked` TINYINT NULL DEFAULT 0,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gamercenter`.`games`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gamercenter`.`games` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `price` DECIMAL(9,2) NULL,
  `is_announced` TINYINT NULL,
  `is_downloadable` TINYINT NULL,
  `score` DOUBLE NULL,
  `description` VARCHAR(2048) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gamercenter`.`game_discounts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gamercenter`.`game_discounts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `start` TIMESTAMP NULL,
  `end` TIMESTAMP NULL,
  `rate` DOUBLE NULL,
  `game_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_discounts_games1_idx` (`game_id` ASC) VISIBLE,
  CONSTRAINT `fk_discounts_games1`
    FOREIGN KEY (`game_id`)
    REFERENCES `gamercenter`.`games` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gamercenter`.`game_comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gamercenter`.`game_comments` (
  `id` INT NOT NULL,
  `parent_id` INT NULL,
  `content` VARCHAR(2048) NULL,
  `created_at` TIMESTAMP(14) NULL,
  `user_id` INT NOT NULL,
  `game_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_comments_users1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_comments_games1_idx` (`game_id` ASC) VISIBLE,
  CONSTRAINT `fk_comments_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `gamercenter`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comments_games1`
    FOREIGN KEY (`game_id`)
    REFERENCES `gamercenter`.`games` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gamercenter`.`game_lists`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gamercenter`.`game_lists` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `users_id` INT NOT NULL,
  `description` VARCHAR(255) NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_personalized_lists_users1_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_personalized_lists_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `gamercenter`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gamercenter`.`game_list_has_games`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gamercenter`.`game_list_has_games` (
  `game_list_id` INT NOT NULL,
  `game_id` INT NOT NULL,
  PRIMARY KEY (`game_list_id`, `game_id`),
  INDEX `fk_personalized_lists_has_games_games1_idx` (`game_id` ASC) VISIBLE,
  INDEX `fk_personalized_lists_has_games_personalized_lists1_idx` (`game_list_id` ASC) VISIBLE,
  CONSTRAINT `fk_personalized_lists_has_games_personalized_lists1`
    FOREIGN KEY (`game_list_id`)
    REFERENCES `gamercenter`.`game_lists` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_personalized_lists_has_games_games1`
    FOREIGN KEY (`game_id`)
    REFERENCES `gamercenter`.`games` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gamercenter`.`game_contents`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gamercenter`.`game_contents` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `type` VARCHAR(45) NULL,
  `path` VARCHAR(255) NULL,
  `game_id` INT NOT NULL,
  PRIMARY KEY (`id`, `game_id`),
  INDEX `fk_images_games1_idx` (`game_id` ASC) VISIBLE,
  CONSTRAINT `fk_images_games1`
    FOREIGN KEY (`game_id`)
    REFERENCES `gamercenter`.`games` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gamercenter`.`user_history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gamercenter`.`user_history` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `users_id` INT NOT NULL,
  `balance_change` DECIMAL(9,2) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `rest_balance` DECIMAL(9,2) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_purchase_history_users1_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_purchase_history_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `gamercenter`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gamercenter`.`posts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gamercenter`.`posts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL,
  `description` VARCHAR(2048) NULL,
  `text` TEXT(65536) NULL COMMENT '1. store as file in file system\n2. html',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `visible` TINYINT NULL DEFAULT 1,
  `author_id` INT NOT NULL,
  `game_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_posts_users1_idx` (`author_id` ASC) VISIBLE,
  INDEX `fk_posts_games1_idx` (`game_id` ASC) VISIBLE,
  CONSTRAINT `fk_posts_users1`
    FOREIGN KEY (`author_id`)
    REFERENCES `gamercenter`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_posts_games1`
    FOREIGN KEY (`game_id`)
    REFERENCES `gamercenter`.`games` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gamercenter`.`post_comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gamercenter`.`post_comments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `parent_id` INT NULL,
  `content` VARCHAR(2048) NULL,
  `created_at` TIMESTAMP NULL,
  `visible` TINYINT NOT NULL DEFAULT 1,
  `user_id` INT NOT NULL,
  `post_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_post_comments_users1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_post_comments_posts1_idx` (`post_id` ASC) VISIBLE,
  CONSTRAINT `fk_post_comments_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `gamercenter`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_post_comments_posts1`
    FOREIGN KEY (`post_id`)
    REFERENCES `gamercenter`.`posts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gamercenter`.`user_friendships`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gamercenter`.`user_friendships` (
  `from_user_id` INT NOT NULL,
  `to_user_id` INT NOT NULL,
  `state` VARCHAR(45) NULL,
  PRIMARY KEY (`from_user_id`, `to_user_id`),
  INDEX `fk_users_has_users_users2_idx` (`to_user_id` ASC) VISIBLE,
  INDEX `fk_users_has_users_users1_idx` (`from_user_id` ASC) VISIBLE,
  CONSTRAINT `fk_users_has_users_users1`
    FOREIGN KEY (`from_user_id`)
    REFERENCES `gamercenter`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_users_users2`
    FOREIGN KEY (`to_user_id`)
    REFERENCES `gamercenter`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gamercenter`.`post_contents`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gamercenter`.`post_contents` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `type` VARCHAR(45) NULL,
  `path` VARCHAR(255) NULL,
  `post_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_post_contents_posts1_idx` (`post_id` ASC) VISIBLE,
  CONSTRAINT `fk_post_contents_posts1`
    FOREIGN KEY (`post_id`)
    REFERENCES `gamercenter`.`posts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gamercenter`.`users_has_games`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gamercenter`.`users_has_games` (
  `user_id` INT NOT NULL,
  `game_id` INT NOT NULL,
  `user_history_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `game_id`),
  INDEX `fk_users_has_games_games1_idx` (`game_id` ASC) VISIBLE,
  INDEX `fk_users_has_games_users1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_users_has_games_user_history1_idx` (`user_history_id` ASC) VISIBLE,
  CONSTRAINT `fk_users_has_games_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `gamercenter`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_games_games1`
    FOREIGN KEY (`game_id`)
    REFERENCES `gamercenter`.`games` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_games_user_history1`
    FOREIGN KEY (`user_history_id`)
    REFERENCES `gamercenter`.`user_history` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
